In [2]:
import numpy as np 

# 합계
n1 = np.sum([1, 2, 3])
print(n1)

# 평균 - 데이터의 평균값
n2 = np.mean([10, 20, 30, 40, 100]) # 40.0
print(n2)

# 중앙값 - 데이터의 중앙에 위치한 값
n3 = np.median([10, 20, 30, 40, 100]) #30.0
print(n3)

# 제곱근 - 양수의 제곱근을 계산
n4 = np.sqrt(16)
print(n4)

6
40.0
30.0
4.0


In [3]:
# 배열 연산 예시
# 1차원 배열 생성
x = np.array([1, 2, 3])
print(x)
print(type(x)) # <class 'numpy.ndarray'>
print(x.shape)  # (3,)

# 인덱싱 및 슬라이싱
print(x[0])  # 1
print(x[-1])  # 3
print(x[1:]) # [2 3]
print(x[:2]) # [1 2]
print(x[:]) # [1 2 3]

# 다른 배열 생성
y = np.array([4, 5, 6])

# 배열 간의 연산
print(x + y)  # [5 7 9]
print(x - y)  # [-3 -3 -3]
print(x * y)  # [ 4 10 18]
print(x / y)  # [0.25 0.4  0.5 ]

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
[2 3]
[1 2]
[1 2 3]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
# 2차원 배열 생성
z = np.array([
  [1, 2, 3], 
  [4, 5, 6]
])
print(z)
print(z.shape)  # (2, 3)

# 2차원 배열의 인덱싱 및 슬라이싱
print(z[0, 0])  # 1
print(z[0, 2])  # 3
print(z[1, 0])  # 4
print(z[1, 1])  # 5

print(z[0])     # [1 2 3]
print(z[1])     # [4 5 6]

print(z[:, 0])  # [1 4]
print(z[:, 1])  # [2 5]
print(z[:, 2])  # [3 6]

[[1 2 3]
 [4 5 6]]
(2, 3)
1
3
4
5
[1 2 3]
[4 5 6]
[1 4]
[2 5]
[3 6]


In [8]:
# array의 차원 변경
a = np.array([1, 2, 3])
print(a.shape)  # (3,)

# 1차원 배열을 2차원 배열로 변경
b = a.reshape(3, 1)
print(b)
print(b.shape)  # (3, 1)

# 2차원 배열의 차원 변경
c = b.reshape(1, 3)
print(c)
print(c.shape)  # (1, 3)

# 2차원 배열을 1차원 배열로 변경
d = b.flatten()
print(d)
print(d.shape)  # (3,)

(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)
[1 2 3]
(3,)


In [6]:
# 결측치
a = np.array([1, 2, np.nan, 4, 5])
print(a)
print(np.isnan(a))  # [False False  True False False]
print(np.sum(a))  # nan

# 결측치를 0으로 대체하여 합계 계산
a_filled = np.where(np.isnan(a), 0, a)
print(np.sum(a_filled))  # 12.0

# 0 생성
zeros_array = np.zeros((2, 3))
print(zeros_array)

# 1 생성
ones_array = np.ones((2, 3))
print(ones_array)

[ 1.  2. nan  4.  5.]
[False False  True False False]
nan
12.0
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
